### ISSUE TITLE
How to get a reference of the current fragment

### ISSUE THREAD

**Issue by MrRuslanYT** [massivemadness/Fragula#15]
Я мог бы переписать библиотеку и добавить метод в NavBackStackAdapter что бы получить фрагмент, но я подумал может существует лучший способ? Я использую свайп фрагмент с вложенными фрагментами внутри, при нажатии на айтем меню мне нужно получить фрагмент что бы вызвать navigate

**Comment by massivemadness** [comment]
Вообще это не считается хорошим тоном, но ссылку любой фрагмент можно получить из childFragmentManager-а

```kotlin
// MainActivity.kt
supportFragmentManager.fragments.first() // FragulaNavHostFragment
    .childFragmentManager.fragments.first() // SwipeBackFragment
    .childFragmentManager.fragments.first { it.isResumed } // CurrentFragment
```

Я бы не добавлял доп. логику для упрощения этого кода, потому что вся суть оригинальной либы была в создании абстракции над фрагментами

**Comment by MrRuslanYT** [comment]
Код работает, спасибо. Только похоже что в MainActivity.onCreate после setContentView нельзя сразу получить CurrentFragment фрагмент, похоже он добавляется позже onCreate

**Comment by MrRuslanYT** [comment]
> Код работает, спасибо. Только похоже что в MainActivity.onCreate после setContentView нельзя сразу получить CurrentFragment фрагмент, похоже он добавляется позже onCreate

Спасибо за помощь, решил с помощью этого кода: 
```
private var mainScreen: MainScreen? = null

binding.fragulaNavHostFragment.getFragment<NavHostFragment>().also {
            swipeController = it.findSwipeController()
            fragulaNavController = it.navController
            val swipeBackFragment = it.childFragmentManager.fragments.first()
            swipeBackFragment.childFragmentManager.registerFragmentLifecycleCallbacks(object : FragmentManager
            .FragmentLifecycleCallbacks() {
                override fun onFragmentCreated(fm: FragmentManager, fragment: Fragment, savedInstanceState: Bundle?) {
                    if (fragment is MainScreen) {
                        mainScreen = fragment
                    }
                }
            }, false)
        }
```
Закрываю issue
