### ISSUE TITLE
minSdk Question 

### ISSUE THREAD

**Issue by MrRuslanYT** [massivemadness/Fragula#16]
В билде minSdk установлен 23, я понизил до 21 в форкнутом репозитории, приложение запускается, есть ли какая то необходимость в установки minSdk как 23 вместо 21? Если нету, то я могу сделать pull request с пониженным sdk.
In the build file minSdk is set to 23, I downgraded to 21 in my forked repo, the app has started, is there a need to set minSdk as 23 instead of 21? If no, I can make a pull request with minSdk 21.

**Comment by massivemadness** [comment]
Кажется это еще со времен разработки первой версии осталось, можешь понизить. Там только придется заменить в одном месте android:foreground чтобы был риппл+фон

**Comment by MrRuslanYT** [comment]
Мне лучше сделать чистый pull request с последнего коммита в develop или с изменениями в моём прошлом пуле https://github.com/massivemadness/Fragula/pull/14?

**Comment by massivemadness** [comment]
Новый от develop
