### ISSUE TITLE
Hi Fragula Bug With viewpager2

### ISSUE THREAD

**Issue by professorDeveloper** [massivemadness/Fragula#29]
hello, if there is viewpager2 in my fragment, scrolling is not working, how to fix it, please help

**Comment by massivemadness** [comment]
Hi @professorDeveloper, this is nested scrolling problem. You can disable fragula viewpager using SwipeController:
```kotlin
val swipeController = findSwipeController()

// onViewCreated
swipeController.setScrollingEnabled(false)

// onDestroyView
swipeController.setScrollingEnabled(true)
```
or something similar

**Comment by professorDeveloper** [comment]
hello thank you very much for the reply now ,I will try and write you an answer, please stay online

**Comment by professorDeveloper** [comment]
@massivemadness 

**bro , I did what you said, and this error occurred**

![image](https://github.com/massivemadness/Fragula/assets/108933534/15ac0975-504b-4978-82b9-49b476835875)

**Comment by massivemadness** [comment]
I'm not sure why this happens, you can try to upgrade JDK version to 17 in your module
```
compileOptions {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
```

**Comment by professorDeveloper** [comment]
It didn't work. Please help me. I couldn't find a good swipe back library for the fragment other than yours. Please help me with this error.  @massivemadness

**Comment by massivemadness** [comment]
Can you tell me which JDK version are you using? You can check it in terminal
`$ java -version`

**Comment by professorDeveloper** [comment]
![image](https://github.com/massivemadness/Fragula/assets/108933534/5bec9339-e7cc-4905-8ed1-491f772c363b)

**Comment by massivemadness** [comment]
Hmm it should work I guess. Maybe you set different version in android studio settings? Check on the screenshot

**Comment by professorDeveloper** [comment]
![image](https://github.com/massivemadness/Fragula/assets/108933534/f9d6bd32-a56d-4e78-ba7e-731df473346a)
@massivemadness

**Comment by massivemadness** [comment]
You're using JDK 11 for this project, try to change Gradle JDK to 17

**Comment by professorDeveloper** [comment]
this worked thanks bro  ❤️ 🔥

> You're using JDK 11 for this project, try to change Gradle JDK to 17

**Comment by massivemadness** [comment]
I'll downgrade it to JDK 11 in the next version
