### ISSUE TITLE
Apply animation to `navigateUp()`

### ISSUE THREAD

**Issue by neslxzhen** [massivemadness/Fragula#6]
**Describe the solution you'd like**
I hope apply scroll animation when call navController().navigateUp()

**Describe alternatives you've considered**
I found accompanist-navigation-animation:0.16.1, which does not have gestures, but does this issue: https://medium.com/androiddevelopers/animations-in-navigation-compose-36d48870776b

Is it possible to combine Fragula with it?

**Comment by massivemadness** [comment]
Hi @neslxzhen , I think it's possible, but I need some time to understand how it works internally. I didn't migrate Fragula on the latest version of NavComponent yet

**Comment by massivemadness** [comment]
Fixed in [v2.6](https://github.com/massivemadness/Fragula/releases/tag/2.6)
